### ISSUE TITLE
2. create a document explaining what you want to achieve

### ISSUE THREAD

**Issue by LTS42** [brianjo94/HospitalEmergeNameEntry#1]
make sure it's a three tier web app

**Comment by LTS42** [comment]
three tier
backend
frontend
database

**Comment by xraycodes** [comment]
What I want to achieve:
Create a simple self registration for patients coming into emergency department 

**Frontend aspect(Using HTML, CSS, Bootstrap):**
1. Home Page HTML page asking for patient to register name, birthday, gender
-Reason for visit
-Email
2. Second html page tells the patient to their # queue in line

**Backend aspect(Using Django):**
Store patient information that they added

**Database aspect(Using SQLlite):**
Store patient information that they added

**Comment by LTS42** [comment]
This is great, let's push this doc to the repo `read.me`

**Comment by xraycodes** [comment]
Updated the readme page

**Comment by LTS42** [comment]
interesting. you were not allowed to push to main branch since we protected it, how did you push? did you disable the protection?

**Comment by brianjo94** [comment]
I just pushed a branch that I made(sidebranch). It didn't let me push to main but I was able to just push the sidebranch  
(git push -u origin sidebranch)

**Comment by xraycodes** [comment]
![image](https://user-images.githubusercontent.com/84826985/205792452-4fdfaaa9-d71e-40d8-85d3-2a0aac32b656.png)
**Created a folder, made commit in the main branch(it won't let me create a branch without commiting from main first). Then created a branch called newbranch, made a dog.txt with cash saved in it. Then commited the new file within the newbranch**

![image](https://user-images.githubusercontent.com/84826985/205792527-fbbba62f-c7e0-44a5-86bb-c736f5e8b33b.png)
**My attempt at uploading remotely. Still in newbranch. Wasn't able to push to main as seen in first error message. However I was able to push the newbranch itself.... **

**Comment by xraycodes** [comment]
![image](https://user-images.githubusercontent.com/84826985/205793986-29930432-3bd9-4c59-93c3-2e296877fd85.png)
**Can you clarify this part? So I merged the newbranch with the main. I understand that the file I made in the newbranch is now there in the main branch. But what is the purpose of this? I cant push this remotely to any of the branches as shown? **

**Comment by LTS42** [comment]
1. delete `dog.txt`
2. delete `xyz`
3. update `UPDATE.md` with what you have commented [here](https://github.com/brianjo94/HospitalEmergeNameEntry/issues/1#issuecomment-1330912016)
