### ISSUE TITLE
0. get wsl environment set up

### ISSUE THREAD

**Issue by LTS42** [brianjo94/HospitalEmergeNameEntry#4]
What is WSL - [link](https://learn.microsoft.com/en-us/windows/wsl/about)
How to set up - [video](https://www.youtube.com/watch?v=_fntjriRe48)

**Comment by xraycodes** [comment]
Complete

**Comment by LTS42** [comment]
show proof by creating a python script that says `hello world` when you run it

**Comment by xraycodes** [comment]
![image](https://user-images.githubusercontent.com/84826985/204591326-d36f8099-7267-4384-b1c0-82312f5342ba.png)

Is this what you mean?

**Comment by LTS42** [comment]
yes, nice
