### ISSUE TITLE
3. pick a framework

### ISSUE THREAD

**Issue by LTS42** [brianjo94/HospitalEmergeNameEntry#5]
shortlist 3 frameworks (mvc)
do a quick pros and cons of 3.
finally pick 1.

some of the suggestions
django (python)
flask (python)
express.js (nodejs)
sails.js (nodejs)
spring boot (java)
...etc

**Comment by xraycodes** [comment]
**Django**
Pros:
-Uses python
-Know how to set up/more knowledgeable than other frameworks(I only know django for web dev atm)
-Can integrate HTML/CSS/Bootstrap
-Has a built in database with liteSQL
-Lots of pre built forms so less coding needed
-Good documentation

Cons:
-May not be the most popular framework
-To be seen
