### ISSUE TITLE
create a barebone django project

### ISSUE THREAD

**Issue by LTS42** [brianjo94/HospitalEmergeNameEntry#6]
requirements:
1. localhost:port/ should should render a simple html that says hello world
2. html must be served as a seperate html
3. no javascript
4. no css

**Comment by LTS42** [comment]
Your host is 127.0.0.1 (same as localhost)
Your port is 8000

`127.0.0.1:8000` should say hello world
you currently have
`127.0.0.1:8000/port`

Let's fix that

**Comment by LTS42** [comment]
been a few days, any progress?
Remember to open a PR (pull request)

**Comment by xraycodes** [comment]
I made the changes. But im struggling to push it using SSH. 
![image](https://user-images.githubusercontent.com/84826985/206790777-fa883b28-04f1-4504-a6ad-a438a4b7fa63.png)
![image](https://user-images.githubusercontent.com/84826985/206790835-755cc196-ce7a-4c9f-ae4c-b28fcd4ae633.png)

Keeps asking for my username and password but the authentication is failing even though my github password is correct.. Last time we did this, we were able to bypass it using my account and email(using SSH) but I'm not too familiar with the steps to do that..

**Comment by xraycodes** [comment]
> I made the changes. But im struggling to push it using SSH. ![image](https://user-images.githubusercontent.com/84826985/206790777-fa883b28-04f1-4504-a6ad-a438a4b7fa63.png) ![image](https://user-images.githubusercontent.com/84826985/206790835-755cc196-ce7a-4c9f-ae4c-b28fcd4ae633.png)
> 
> Keeps asking for my username and password but the authentication is failing even though my github password is correct.. Last time we did this, we were able to bypass it using my account and email(using SSH) but I'm not too familiar with the steps to do that..

**UPDATE**
So I was able to overwrite/replace the previous remote address(which I think was using the https link) to the SSH link using git remote set-url as shown in image below. 
![image](https://user-images.githubusercontent.com/84826985/206794307-031e0c9d-00d3-4078-83ae-e8db28ea5dc0.png)

However, even though I tried git push I got this message(Saying the branch has no upstream branch) and I should enter the following code instead( git push --set-upstream origin fixinghomepage) .. Is this still correct?
![image](https://user-images.githubusercontent.com/84826985/206794076-f0a19206-8282-4394-8dde-1f82736aae21.png)

**Comment by LTS42** [comment]
yes, it seems like it worked.
navigate to [here](https://github.com/brianjo94/HospitalEmergeNameEntry/branches) to check.
make sure to open a PR (pull request)

**Comment by xraycodes** [comment]
Can we close this issue? Or did you want me to do something else to the barebone? :)

**Comment by LTS42** [comment]
yes
